name: Generate Hacker Snake Animation
on:
  schedule:
    - cron: "0 */12 * * *" # update tiap 12 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run Hacker Snake Generator
        run: node src/hacker-snake.js
      - name: Commit SVG to output branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout -B output
          git add hacker-snake.svg
          git commit -m "Update hacker snake animation"
          git push origin output --force
